---
layout: post
title: "Something witty about Excel"
author: "Brian Davis"
date: "`r format(Sys.time(), '%d %B, %Y')`"
published: false
status: process
draft: false
output: html_document
---

seqMeta 1.6.0 Released 

Last night I attended my firt Houston R USers Group in a really long time (5ish years???).  The first topic was reading data from Excel with readxl.  
 [ TBD ]
Notes on R and Excel


## Four Main R-Excel that can read & write

A good overview of the


## seqMeta 1.6.0

* Migrated to git / github
    + Bug Reports and Feature Requests should be submitted [github](https://github.com/DavisBrian/seqMeta/issues).
* Minimum R version moved to 3.1.0
* Duplicated SNP in snpinfo gene no longer pulls from the genotype matrix twice.
* Monomorphic snps with caf != 0 were handled incorrectly.
* Binomial models when genotypes imputed outside of seqMeta did not match when models were imputed by seqMeta.  Very slight differences in the covariance structure.
* Replaced `any(is.na(Z))` with `anyNA(Z)`
* Genotype range test now checks that they are [0, 2].
* SNPInfo in seqMetaExamples had incorrect type of snpNames and aggregateBy.
* Automatically convert (with warning) aggregateBy and snpName columns to type character if they are not already.
* Added new function prepScores2


### prepScores2

prepScores2 is a drop in replacement for prepScores, prepScoresX and prepCox. The only difference is the family argument should be text. `gaussian()` becomes `"gaussian"`, `binomial()` becomes `"binomial"` and `"cox"` is used for survival models. 
